# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-application
  labels:
    app: golang-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-application
  template:
    metadata:
      labels:
        app: golang-application
    spec:
      containers:
      - name: golang-application
        image: sh1vam6/go-web-app:{{ .Values.image.tag }}

        ports:
        - containerPort: 8080